export const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
export const SET_CURRENT_ITEM = 'SET_CURRENT_ITEM';
export const REQUEST_ARTICLE_BY_DATE = 'REQUEST_ARTICLE_BY_DATE';
export const RECEIVE_ARTICLE_BY_DATE = 'RECEIVE_ARTICLE_BY_DATE';
export const REQUEST_ARTICLES = 'REQUEST_ARTICLES';
export const RECEIVE_ARTICLES = 'RECEIVE_ARTICLES';
export const FILTER_SOURSE = 'FILTER_SOURSE';
